language: go
go:
  - 1.7.5
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

before_deploy:
  - gox -osarch "linux/amd64 linux/arm" -output "dist/{{.Dir}}/{{.OS}}_{{.Arch}}"
deploy:
  provider: script
  script: ghr -u levinalex $TRAVIS_TAG dist
  skip_cleanup: true
  on:
    tags: true
    go: 1.7.5
